services:
  nginx:
    build: ./nginx
    image: nginx
    networks:
      my_net:
        ipv4_address: 1.2.3.2
    ports:
      - "80:80"
      - "443:443"  
    volumes:
      - vol:/var/www/html/


  sshd:
    build: ./sshd
    image: sshd
    networks:
      my_net:
        ipv4_address: 1.2.3.3
    volumes:
      - vol:/home/tplover

  sentinelle:
    build: ./sentinelle
    image: sentinelle
    networks:
      my_net:
        ipv4_address: 1.2.3.4
    volumes:
      - vol:/doss



volumes:
  vol:

networks:
  my_net:
    ipam:
      driver: default
      config:
        - subnet: 1.2.3.0/24
          gateway: 1.2.3.1
